### PR TITLE
Remove t.co redirection even on profile website link

### LINKED ISSUE #416: "Remove t.co redirection on links" not working with profile website link
When opening a profile, website link is a t.co link even with this option enabled.

firefox_2019-03-29_13-04-41

### PR DESCRIPTION
**Pull request by hiroto7**
Fixes #416.

Since the method `createUrlAnchor()` is not called when rendering the profile website link, I added template modification.

### CODE REVIEW

File: src/features/removeRedirection.ts [hunk 1]
```diff
@@ -29,4 +30,16 @@ export const maybeRemoveRedirection = makeBTDModule(({TD, settings}) => {
 
     return result;
   };
+
+  TD.services.TwitterUser.prototype.getExpandedURL = function () {
+    return this.entities.url.urls[0].expanded_url;
```
Comment (eramdam) [inline src/features/removeRedirection.ts:35]: Could we add some checks here? I feel like this might crash if a given user doesn't have an url?

**Review by eramdam — CHANGES_REQUESTED** [review]
Thanks for this 🙇‍♂️ Overall looks good, just left a small comment

File: src/features/removeRedirection.ts (hunk 1 above)
Comment (hiroto7) [reply src/features/removeRedirection.ts:35]: As far as the code in this PR, `getExpandedURL()` is not called for users who do not have a website link so that no crash will occur. 
However, with this, templates such as `{{# getExpandedURL}} ... {{/ getExpandedURL}}` cause crash, now I think we should add an existence check too.

So, I'll add the check similar to `TD.services.TwitterUser.prototype.getDisplayURL` (implemented by original TweetDeck)

Comment (eramdam) [reply src/features/removeRedirection.ts:35]: @hiroto7 sounds good! I prefer to be extra careful because crashing in there can have weird consequences 😅

Comment (hiroto7) [reply src/features/removeRedirection.ts]: I added it in 84ead19.

**Review by eramdam — APPROVED** [review]
